### ISSUE TITLE
jenkins snyk plugin java.lang.OutOfMemoryError: Java heap space.  during final stage

### ISSUE THREAD

**Issue by chrislin22** [jenkinsci/snyk-security-scanner-plugin#114]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
 Jenkins: 2.303.3.3
OS: Linux - 4.15.0-147-generic
---
snyk-security-scanner:3.2.3
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

linux/linux

### Reproduction steps

```
snykSecurity(
  snykInstallation: 'snyk@latest',
  snykTokenId: 'SNYK_API_TOKEN',
  organisation:'${SNYK_PILOT_ORG_ID}',
  failOnIssues: false,
  additionalArguments: '--all-projects '
)
```

### Expected Results

success

### Actual Results

```
17:09:43  2022-03-07T22:08:50.808Z snyk sending request to: https://snyk.io/api/v1/analytics/cli
17:09:43  2022-03-07T22:08:50.808Z snyk request body size: 194502249
17:09:43  2022-03-07T22:08:50.808Z snyk gzipped request body size: 4015208
17:09:43  2022-03-07T22:08:50.809Z snyk not using proxy
17:09:43  2022-03-07T22:08:50.812Z snyk Exit code: 1
17:10:08  FATAL: Snyk Security scan failed.
17:10:08  java.io.IOException: Remote call on agent-1756 failed
17:10:08  	at hudson.remoting.Channel.call(Channel.java:1005)
17:10:08  	at hudson.FilePath.act(FilePath.java:1166)
17:10:08  	at hudson.FilePath.act(FilePath.java:1155)
17:10:08  	at hudson.FilePath.readToString(FilePath.java:2294)
17:10:08  	at io.snyk.jenkins.SnykTest.testProject(SnykTest.java:65)
17:10:08  	at io.snyk.jenkins.SnykStepFlow.testProject(SnykStepFlow.java:62)
17:10:08  	at io.snyk.jenkins.SnykStepFlow.perform(SnykStepFlow.java:36)
17:10:08  	at io.snyk.jenkins.workflow.SnykSecurityStep$Execution.run(SnykSecurityStep.java:172)
17:10:08  	at io.snyk.jenkins.workflow.SnykSecurityStep$Execution.run(SnykSecurityStep.java:159)
17:10:08  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
17:10:08  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17:10:08  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17:10:08  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
17:10:08  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
17:10:08  	at java.lang.Thread.run(Thread.java:748)
17:10:08  Caused by: java.lang.OutOfMemoryError: Java heap space
17:10:08  	at java.util.Arrays.copyOf(Arrays.java:3332)
17:10:08  	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
17:10:08  	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
17:10:08  	at java.lang.StringBuilder.append(StringBuilder.java:190)
17:10:08  	at java.io.ObjectInputStream$BlockDataInputStream.readUTFSpan(ObjectInputStream.java:3632)
17:10:08  	at java.io.ObjectInputStream$BlockDataInputStream.readUTFBody(ObjectInputStream.java:3540)
17:10:08  	at 
```

### Anything else?

directly run the installed snyk by the jenkins plugin runs successfully:

`/home/jenkins/tools/io.snyk.jenkins.tools.SnykInstallation/snyk_latest/snyk-linux monitor --json --org=**** --all-projects`

**Comment by chrislin22** [comment]
My best guess is the snyk plugin need a configuration option to allow set larger heap size
