### ISSUE TITLE
Javascript and Dotnet analysis fails after Jenkins upgrade

### ISSUE THREAD

**Issue by mortenkri** [jenkinsci/snyk-security-scanner-plugin#128]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>
  ```text
Jenkins: 2.361
OS: Linux - 5.4.0-1067-azure
---
ace-editor:1.1
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
apimap:1-rc24.468d98ec1b_48
authentication-tokens:1.4
basic-branch-build-strategies:1.3.2
blueocean:1.25.5
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.25.5
blueocean-commons:1.25.5
blueocean-config:1.25.5
blueocean-core-js:1.25.5
blueocean-dashboard:1.25.5
blueocean-display-url:2.4.1
blueocean-events:1.25.5
blueocean-git-pipeline:1.25.5
blueocean-github-pipeline:1.25.5
blueocean-i18n:1.25.5
blueocean-jwt:1.25.5
blueocean-personalization:1.25.5
blueocean-pipeline-api-impl:1.25.5
blueocean-pipeline-editor:1.25.5
blueocean-pipeline-scm-api:1.25.5
blueocean-rest:1.25.5
blueocean-rest-impl:1.25.5
blueocean-web:1.25.5
bootstrap4-api:4.6.0-5
bootstrap5-api:5.1.3-7
bouncycastle-api:2.26
branch-api:2.1046.v0ca_37783ecc5
build-monitor-plugin:1.13+build.202205140447
build-timeout:1.21
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.7.4
cloudbees-bitbucket-branch-source:784.v7fcdc7c670f6
cloudbees-disk-usage-simple:170.va_fd5b_4ee6858
cloudbees-folder:6.736.v5f554b_b_a_52b_3
command-launcher:84.v4a_97f2027398
configuration-as-code:1512.vb_79d418d5fc8
credentials:1139.veb_9579fca_33b_
credentials-binding:523.vd859a_4b_122e6
crowd2:3.1.2
dark-theme:185.v276b_5a_8966a_e
display-url-api:2.3.6
durable-task:496.va67c6f9eefa7
echarts-api:5.3.3-1
email-ext:2.91
embeddable-build-status:237.v37e2c03964c9
extended-read-permission:3.2
favorite:2.4.1
font-awesome-api:6.1.1-1
git:4.11.4
git-client:3.11.1
git-server:1.11
github:1.34.5
github-api:1.303-400.v35c2d8258028
github-branch-source:1677.v731f745ea_0cf
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.30
instance-identity:3.1
jackson2-api:2.13.3-285.vc03c0256d517
jakarta-activation-api:2.0.0-3
jakarta-mail-api:2.0.0-6
javax-activation-api:1.2.0-4
javax-mail-api:1.6.2-7
jaxb:2.3.6-1
jdk-tool:1.5
jenkins-design-language:1.25.5
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.15-1
job-dsl:1.77
jquery3-api:3.6.0-4
jsch:0.1.55.2
junit:1119.1121.vc43d0fc45561
kubernetes:3670.v6ca_059233222
kubernetes-client-api:5.12.2-193.v26a_6078f65a_9
kubernetes-credentials:0.9.0
kubernetes-credentials-provider:1.196.va_55f5e31e3c2
ldap:2.11
lockable-resources:2.16
mailer:435.v79ef3972b_5c7
material-theme:0.4.1
matrix-auth:2.6.11
matrix-project:772.v494f19991984
metrics:4.2.10-389.v93143621b_050
mina-sshd-api-common:2.8.0-36.v8e25ce90d4b_1
mina-sshd-api-core:2.8.0-36.v8e25ce90d4b_1
momentjs:1.1.1
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.8
pipeline-build-step:2.18
pipeline-github-lib:38.v445716ea_edda_
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-groovy-lib:598.vcd66b_a_336510
pipeline-input-step:449.v77f0e8b_845c4
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2114.v2654ca_721309
pipeline-model-definition:2.2114.v2654ca_721309
pipeline-model-extensions:2.2114.v2654ca_721309
pipeline-rest-api:2.24
pipeline-stage-step:293.v200037eefcd5
pipeline-stage-tags-metadata:2.2114.v2654ca_721309
pipeline-stage-view:2.24
pipeline-utility-steps:2.13.0
plain-credentials:1.8
plugin-util-api:2.17.0
popper-api:1.16.1-3
popper2-api:2.11.5-2
prometheus:2.0.11
pubsub-light:1.16
resource-disposer:0.19
scm-api:616.ve67136f6c77d
script-security:1175.v4b_d517d6db_f0
slack:616.v03b_1e98d13dd
snakeyaml-api:1.30.2-76.vc104f7ce9870
snyk-security-scanner:3.2.6
sonar:2.14
sse-gateway:1.25
ssh-agent:295.v9ca_a_1c7cc3a_a_
ssh-credentials:295.vced876c18eb_4
ssh-slaves:1.834.v622da_57f702c
sshd:3.242.va_db_9da_b_26a_c3
startup-trigger-plugin:2.9.3
strict-crumb-issuer:2.1.0
structs:324.va_f5d6774f3a_d
theme-manager:1.4
timestamper:1.18
token-macro:308.v4f2b_ed62b_b_16
trilead-api:1.67.vc3938a_35172f
variant:59.vf075fe829ccb
view-job-filters:2.3
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1188.v0016b_4f29881
workflow-basic-steps:980.v82219a_ed188e
workflow-cps:2759.v87459c4eea_ca_
workflow-durable-task-step:1199.v02b_9244f8064
workflow-job:1207.ve6191ff089f8
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:833.va_1c71061486b_
ws-cleanup:0.42
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

1. Analyse a Dotnet or a Javascript (npm) project using the Jenkins Snyk Plugin.
2. Use a remote agent (we are in Azure and are using Linux agents).

### Expected Results

We expect this this to work (it did prior to Jenkins upgrade).

### Actual Results

Testing project...

> /home/jenkins/tools/snyk/snyk-linux test --json --severity-threshold=high --org=XXX --fail-on=upgradable --all-projects

FATAL: Snyk Security scan failed.

java.nio.charset.MalformedInputException: Input length = 1

	at java.base/java.lang.StringCoding.throwMalformed(Unknown Source)

	at java.base/java.lang.StringCoding.throwMalformed(Unknown Source)

	at java.base/java.lang.StringCoding.newStringNoRepl1(Unknown Source)

	at java.base/java.lang.StringCoding.newStringNoRepl(Unknown Source)

	at java.base/java.lang.System$2.newStringNoRepl(Unknown Source)

	at java.base/java.nio.file.Files.readString(Unknown Source)

	at hudson.FilePath$ReadToString.invoke(FilePath.java:2377)

	at hudson.FilePath$ReadToString.invoke(FilePath.java:2372)

	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3492)

	at hudson.remoting.UserRequest.perform(UserRequest.java:211)

	at hudson.remoting.UserRequest.perform(UserRequest.java:54)

	at hudson.remoting.Request$2.run(Request.java:376)

	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)

	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:126)

	at java.base/java.lang.Thread.run(Unknown Source)

	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from xx.xxx.xx.xxx/xx.xxx.xx.xxx:xxxxx

		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)

		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)

		at hudson.remoting.Channel.call(Channel.java:1000)

		at hudson.FilePath.act(FilePath.java:1186)

		at hudson.FilePath.act(FilePath.java:1175)

		at hudson.FilePath.readToString(FilePath.java:2369)

		at io.snyk.jenkins.SnykTest.testProject(SnykTest.java:65)

		at io.snyk.jenkins.SnykStepFlow.testProject(SnykStepFlow.java:62)

		at io.snyk.jenkins.SnykStepFlow.perform(SnykStepFlow.java:36)

		at io.snyk.jenkins.workflow.SnykSecurityStep$Execution.run(SnykSecurityStep.java:172)

		at io.snyk.jenkins.workflow.SnykSecurityStep$Execution.run(SnykSecurityStep.java:159)

		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)

		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

		at java.base/java.lang.Thread.run(Thread.java:829)

Snyk failed to scan your project. Input length = 1

### Anything else?

We recently upgraded Jenkins (from 2.354 to 2.361) and also upgraded all plugins. We have CI pipelines running Snyk for Java (Maven/Gradle), Golang, Javascript (NPM) and Dotnet. After the upgrade only Java and Go analysis still works. But for Javascript and Dothet the error (as above) occurs.

**Comment by mortenkri** [comment]
The Snyk plugin was not upgraded since this was already at the latest version.

**Comment by bastiandoetsch** [comment]
Hi Morten, would you please open a Zendesk ticket? We don't use issues here for such cases. Sorry for the inconvenience.
